### PR TITLE
fix(security): run execute_typescript sandbox as non-root user

### PR DESCRIPTION
**Pull request by AmirF194**
Container mode's `docker run` / `podman run` invocation for `execute_typescript` never set `--user`, so the sandbox ran as the operator-configured image's default user, which is root for `node:20-alpine` (the default) and most other images. A container-runtime escape or a setuid/setgid exploit inside the guest hands back root rather than an unprivileged uid.

## Fix

Run the container as a fixed non-root uid:gid (`65532:65532`, the distroless "nonroot" convention) rather than a named user, since the operator-configured image is not guaranteed to define one.

The non-root user has no writable `$HOME` on the image's own filesystem, and `npx` needs one: installing `tsx`'s `esbuild` dependency spawns a native binary out of `$HOME`'s npm cache, which cannot live on the existing `/tmp` tmpfs because that one is intentionally `noexec` (defense in depth for the executed code itself). This PR adds a second, exec-allowed tmpfs at `/home/sandbox` with `$HOME` pointed there, so the two stay separate.

Scoped to item 2 of #157 only (non-root user). Items 1, 3 and 4 (egress control, a prebuilt tsx image, explicit seccomp) are separate, broader changes; #157's own thread already downgrades this item to backlog/defense-in-depth since the hosted deployment has `execute_typescript` disabled, so I kept the diff to exactly this one change.

## Verification

- New regression test (`tests/security/test_sandbox_nonroot_user.py`) fails on unpatched `main` (no `--user` flag, no `HOME=`) and passes on this branch; confirmed with a Docker differential against both.
- Manually reproduced the interaction this fix has to get right: a naive `--user` plus `HOME=/tmp` breaks `npx tsx` outright, since `/tmp` is noexec and `esbuild`'s postinstall needs to exec its downloaded binary (`EACCES` from `spawnSync`). Verified live in a `node:20-alpine` container that the separate exec-allowed `/home/sandbox` tmpfs fixes that while a plain `--user 65532:65532` with no `$HOME` change does not.
- `tests/security/`, `tests/tools/test_code_execution.py`, and the full suite pass unchanged (`ruff check`, `mypy src/`, `pytest`), run in Docker on Python 3.10 and 3.13 in addition to 3.12; the two pre-existing `test_closing_keyword_guard.py` failures on 3.10 reproduce identically on unpatched `main` in the same container (no `git` binary in `python:3.10-slim`), unrelated to this change.
- Did not check coverage numerically (the repo's beartype import hook conflicts with `coverage`/`pytest-cov` in this container); both changed code paths are read back and asserted on directly by the new test's captured `argv`.

Refs #157

### CODE REVIEW

**Review by vishalsachdev — CHANGES_REQUESTED** [review]
Thanks for this — the mechanism is right, the scope discipline is exactly what I asked for on #157, and I verified the regression test is real: it fails on unpatched `main` (`'--user' not in [...]`, `no HOME= passed`) and passes on this branch; `tests/security` + `test_code_execution.py` are green (622 passed).

One thing the argv-level test cannot see, which I believe breaks container mode on a Linux host:

- The script the container runs is created with `tempfile.NamedTemporaryFile` (`code_execution.py:500`), which always yields **mode 0600** owned by the host user, and the `.cjs` guard that `NODE_OPTIONS --require`s is explicitly `chmod 0o600` (line 243). Both sit inside the `/workspace:ro` bind mount.
- With `--user 65532:65532`, neither file is readable by the container process on a plain Linux bind mount — `tsx` cannot open the script and Node cannot load the guard, so every execution fails with `EACCES` before user code runs. Docker Desktop on macOS remaps ownership through its file-sharing layer, which would hide this in a local check.

Could you (1) make the two temp files world-readable (`0o644`) in container mode — the 0600 was for a local-mode threat that does not apply when the workspace is read-only inside the guest — and (2) confirm an end-to-end `execute_typescript` run on a Linux Docker host (not Docker Desktop for Mac)? If you don't have a Linux box handy, say so and I will run it.

I have approved the Actions run so CI will report on the next push.

**Comment by vishalsachdev** [comment]
CI ran after approval and every test job fails on collection, independent of the finding above:

```
ImportError while importing test module 'tests/security/test_sandbox_nonroot_user.py'
E   ModuleNotFoundError: No module named 'tests.security'
```

`from tests.security.test_sandbox_fail_closed import get_execute_typescript` only resolves when the repo root happens to be on `sys.path` (it did in my local run, which is why I saw green). No other test file imports across test modules this way. Simplest fix: move `get_execute_typescript` into a shared fixture/helper (e.g. `tests/security/conftest.py`) and import it from there in both files, or inline a copy in the new test.

**Comment by AmirF194** [comment]
Both fixed and pushed.

1. Import: moved get_execute_typescript into test_sandbox_nonroot_user.py directly instead of importing it via tests.security, since that only resolved when the repo root happened to be on sys.path.

2. Permissions: chmod both the code file and the network-guard file to 0644 in container mode. Confirmed the mechanism directly on a Linux Docker host: a 0600 file in a read-only bind mount gives `cat: can't open: Permission denied` under `--user 65532:65532`, and 0644 reads clean. Added a test asserting both files get chmod'd to 0644 when sandbox_mode is container.

**Comment by vishalsachdev** [comment]
Follow-up on b28ae4b. CI has now run on this head: both required checks (`test-enhancements`, `lint`) plus the 3.10 to 3.13 matrix and the security suite are green. Locally: 1401 passed / 21 skipped on the head and on a merge with current `main`, `ruff` and `mypy` clean, and the new test still fails on unpatched `main` (3 failures) and passes here, so it is not vacuous. Both items from my earlier review are addressed.

Two new things came in before I could merge, and I want to settle them with you rather than wave them through.

**1. CodeQL flagged both `chmod 0o644` calls** (alerts 145 and 146, `py/overly-permissive-file`, high). A second independent review pass raised the same point for the `.ts` script specifically: on a multi-user Linux host, `code_api/` is traversable, so while a run is in flight any local account can read the submitted script, and bulk grading scripts can carry student IDs, grades, or comments in literals. The `.cjs` guard is different: it contains only the allowlist hosts, so 0644 there costs nothing and I am fine dismissing that alert with a note.

For the script itself I see three options and would like your view:
- (a) Keep 0644, document the multi-user-host caveat next to `TS_SANDBOX_MODE`, dismiss the alert. Simplest, and it is the only variant that also works under rootless podman, where the host user's files appear root-owned inside the container.
- (b) Feed the script over stdin instead of writing it into the bind mount: `-i` is already passed, so `sh -c 'cat > "$HOME/code.ts" && npx tsx "$HOME/code.ts"'` with the code piped in would leave no host-side copy at all and the file would live only in the exec-allowed `$HOME` tmpfs. Needs `stdin=PIPE` in the subprocess call and a Linux end-to-end run.
- (c) `--user 65532:<host gid>` with 0640. Narrower than world-readable, but breaks rootless podman for the reason above, and the project has said podman must keep working.

**2. The same review pass called the exec-allowed `$HOME` tmpfs a P1** ("writable and executable, bypasses `/tmp:noexec`"). I checked that against the code and I do not think it is a regression: the invocation has no `--read-only`, so before this PR the container ran as root on a fully writable and executable rootfs, and `/tmp:noexec` was never a complete barrier. After this PR the only writable-and-executable location for uid 65532 is the 64 MB `/home/sandbox` tmpfs. That is a smaller surface than before, not a larger one. It does suggest a cheap follow-up that this PR makes possible: add `--read-only` to the run, since the rootfs no longer needs to be writable once `$HOME` and `/tmp` are tmpfs. Happy to file that separately.

I have not done the end-to-end run on a Linux Docker host either; there is no Docker daemon on the machine I am reviewing from today. If you have one handy and can paste a sanitized `execute_typescript` result from this branch, that closes the last open request from the first review.

Once we pick (a), (b), or (c) I will update the branch against `main` and merge. Note for whoever merges: the first commit's message ends with a `Fixes #157` line, and #157 covers four items of which this PR is one, so the squash message needs that line removed or #157 reopened right after.

**Comment by vishalsachdev** [comment]
@AmirF194 decision on the 0644 question: we go with option (b), stdin delivery.

Concretely: `-i` is already passed on the `docker run` / `podman run` line, so run the container command as

```
sh -c 'cat > "$HOME/code.ts" && npx tsx "$HOME/code.ts"'
```

with `stdin=asyncio.subprocess.PIPE` in the `create_subprocess_exec` call and the script bytes written to it, then stdin closed. The script then lives only in the exec-allowed `$HOME` tmpfs inside the container, no host-side copy exists during the run, and CodeQL alert 145 resolves by construction rather than by dismissal. Rootless podman keeps working because nothing on the host needs to be readable by the container uid any more. The `.cjs` network guard stays as it is (0644, it only contains allowlist hosts); I have dismissed alert 146 for it with that rationale.

Two asks:
1. Make the change on your branch. The `NamedTemporaryFile` for the `.ts` script is then only needed in local mode; container mode should not write it at all.
2. Paste a sanitized `execute_typescript` result from an end-to-end run on a Linux Docker host with the new branch. We have no Docker host available this week, and you already have the differential setup from the permission test.

Note for the merge: the squash message will drop the `Fixes #157` trailer from your first commit. #157 covers four items and this PR closes one of them, so the issue stays open; nothing you need to change for that.

**Comment by AmirF194** [comment]
Pushed c60453e with the stdin-delivery change.

In container mode the script is no longer written to a host-side temp file at all. `create_subprocess_exec` now passes `stdin=asyncio.subprocess.PIPE` and the container command is `sh -c 'cat > "$HOME/code.ts" && npx tsx "$HOME/code.ts"'`, with the code bytes sent to `communicate(input=...)`. Local mode is unchanged and still uses `NamedTemporaryFile`. The `.cjs` network guard is untouched, still a real file at 0644.

Updated the container-mode permissions test to expect one chmod call (guard only) and added a test asserting the code goes over stdin and `NamedTemporaryFile` is never called with the `.ts` suffix in container mode.

End-to-end run on this branch, on a Linux host with Docker (no Docker Desktop remap involved), calling execute_typescript directly rather than through the argv-level test mocks:

```
Mode: container
Output:
stdin-delivery check
uid:gid = 65532:65532
HOME = /home/sandbox
4
```

A separate run held the container for a few seconds with a host-side watcher polling code_api/ every 50ms; it saw zero .ts files appear there at any point during the run. Also ran once with the default network guard on (block_outbound=true) and registry.npmjs.org allowlisted, so the guard file, its chmod, and stdin code delivery all exercised together in the same call; same uid:gid and HOME, same output.

tests/security full suite: 585 passed, 18 skipped. Full tests/: 1403 passed, 20 skipped, matching your CI invocation (pytest tests/ -q). ruff and mypy clean on src/.

Pasted the docstring update too: execute_typescript now says code runs from a temp file in local mode and is streamed in container mode, since the old wording was file-based for both.

**Comment by AmirF194** [comment]
One more finding worth flagging before this settles: CodeQL caught the same pattern on the network-guard file, chmod 0644 at line 476, added by this PR for the same reason as the code file (container uid 65532 needs read access on the ro bind mount). The guard script itself carries no secrets or tokens, only the allowlist and patch logic, so the exposure is lower than the code file was. I have not found a clean fix that avoids world-readable without either chown to 65532 (needs host privileges I cannot verify here) or an idmapped bind mount. Given how deliberately you have been walking through this file's permission model, would you rather I try the chown-with-fallback approach or are you fine leaving this one at 0644 given the lower-sensitivity content?

**Comment by vishalsachdev** [comment]
@AmirF194 thanks for the fast turnaround on (b). Two things.

**The 0644 on the guard file: leave it.** Same reasoning as alert 146 yesterday. The `.cjs` holds the allowlist and the patch logic, nothing a local user gains by reading, and the container uid has to read it through the `:ro` mount somehow. chown-with-fallback would add a privileged path we cannot test on rootless podman for no confidentiality gain. I will dismiss the CodeQL alert with that rationale when this merges.

**One regression in c60453e, fixed in 877a3a1 (pushed to your branch).** The tool tells the model to write `import { bulkGrade } from './canvas/grading/bulkGrade.js'`, and that path resolves relative to the script file. When the script lived in `code_api/` it worked; from `$HOME/code.ts` it fails with `Cannot find module './canvas/...'` for every real bulk-grading script. Your end-to-end script had no imports, so it could not show this. Measured locally with tsx (same resolution rule, no container needed):

```
script inside code_api/          -> function
script in a HOME-like dir        -> Error: Cannot find module './canvas/assignments/listSubmissions.js'
same dir + symlinked canvas/     -> function
```

The fix keeps your design (script only ever on the tmpfs, delivered over stdin) and adds a run directory that symlinks the workspace's `canvas/` (and `node_modules/` when the operator installed it) before the script is written beside them. New test `test_stdin_script_can_still_import_canvas_modules` pins it. Suite 1456 passed, ruff and mypy clean.

If you have the Linux Docker host handy, one more run with a script that actually imports from `./canvas/` would be a useful confirmation, but I am not blocking the merge on it.

**Comment by AmirF194** [comment]
Thanks for catching the module resolution regression and fixing it directly, that is exactly the failure mode stdin delivery could hit and I would not have found it without a Linux Docker host to test against. Appreciate you walking through the CodeQL alerts and the podman constraint in that much detail too.
